FROM java:8-jdk-alpine
RUN sh -c 'mkdir /usr/app'
COPY ./target/back-0.0.1-SNAPSHOT.jar /usr/app
COPY ./firebase-sdk.json /usr/app
WORKDIR /usr/app
RUN sh -c 'touch back-0.0.1-SNAPSHOT.jar'
ENTRYPOINT ["java","-jar","back-0.0.1-SNAPSHOT.jar"]